crop_reasons = {
    "rice": "Rice thrives in warm, humid climates with consistent rainfall and water-retentive soil — perfect for monsoon or irrigated regions.",
    "wheat": "Wheat is ideal for cooler climates with moderate rainfall and loamy soil — great for post-monsoon rabi season.",
    "maize": "Maize grows well in well-drained soil with warm temperatures and moderate humidity — ideal for kharif or summer cropping.",
    "chickpea": "Chickpeas need less water and grow best in cool, dry climates — suitable for semi-arid zones during rabi season.",
    "kidneybeans": "Kidney beans require moderate temperatures and moisture — best grown in fertile soil after monsoon rains.",
    "pigeonpeas": "Pigeon peas are drought-tolerant and thrive in semi-arid climates — good for rainfed regions with less irrigation.",
    "mothbeans": "Moth beans tolerate high heat and drought — ideal for dry, sandy, or semi-arid regions with minimal rainfall.",
    "mungbean": "Mungbeans are short-duration crops that do well in warm climates with moderate rainfall — suitable for intercropping too.",
    "blackgram": "Black gram is hardy and drought-tolerant, suited to warm and moderately dry conditions — good for late kharif.",
    "lentil": "Lentils grow in cool climates with low to moderate rainfall — best for post-monsoon (rabi) cultivation in light soil.",
    "pomegranate": "Pomegranates thrive in hot, dry climates with well-drained soil — ideal for arid or semi-arid regions.",
    "banana": "Bananas require high humidity, warm temperatures, and rich, moist soil — perfect for tropical and sub-tropical zones.",
    "mango": "Mango trees love warm, dry climates for flowering and ripening — suitable for alluvial or well-drained soil regions.",
    "grapes": "Grapes need long, warm growing seasons and less rainfall — best suited for dry regions with controlled irrigation.",
    "watermelon": "Watermelons need high heat and low humidity — ideal for sandy loam soil in hot, dry climates.",
    "muskmelon": "Muskmelons prefer warm, dry weather with low humidity — good for well-drained, sandy soils during summer.",
    "apple": "Apples grow well in cool temperate climates with chilling winters — suitable for hilly and mountainous regions.",
    "orange": "Oranges grow in semi-tropical climates with well-drained sandy loam soil and moderate rainfall — ideal for central and south India.",
    "papaya": "Papayas require warm weather and frequent moisture — ideal for tropical climates with organic-rich soils.",
    "coconut": "Coconuts thrive in high rainfall and coastal humid areas — best for sandy and loamy soil near sea level.",
    "cotton": "Cotton grows best in black soil with high temperature and light rainfall — perfect for dry inland regions.",
    "jute": "Jute requires warm weather with heavy rainfall — ideal for alluvial soil near rivers in eastern India.",
    "coffee": "Coffee thrives in cool, shaded, high-altitude tropical areas with regular rainfall — best for hill plantations."
}
